Shopping/Shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shopping/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [ 
    path('',views.Store,name='store'),
    path('cart/',views.Cart,name='cart'),
    path('checkout/',views.Checkout,name='checkout'),
]

Shopping/store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User,null=True,blank=True,on_delete=models.CASCADE)
    name = models.CharField(max_length=100,null=True)
    email = models.EmailField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    digital = models.BooleanField(default=False,null=True,blank=True)
    image = models.ImageField(upload_to="",null=True,blank=True)
    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True,blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100,null=True)

    def __str__(self):
        return str(self.id)
    
    @property
    def get_cart_total(self):
        items = self.orderitem_set.all()
        total = sum([item.product.price for item in items])
        return total

    @property
    def get_number_of_items(self):
        items = self.orderitem_set.all()
        total = sum([1 for item in items])
        return total

class OrderItem(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    product = models.ForeignKey(Product,on_delete=models.SET_NULL,null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL,null=True)
    quantity = models.IntegerField(default=0,null=True,blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def cost(self):
        return self.quantity*self.product.price
class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL,null=True)
    address = models.CharField(max_length=200)
    city= models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    pincode = models.CharField(max_length=6)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address
    

Shopping/store/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def Cart(request):
    if request.user.is_authenticated:
        Customer = request.user.customer
        orderitems = OrderItem.objects.filter(customer=Customer)
        order = orderitems[0].order
    else :
        orderitems = []
        order = {'get_cart_total':0,'get_number_of_items':0}
    context={'items':orderitems,'order':order}
    return render(request,'store/cart.html',context)

def Checkout(request):
    if request.user.is_authenticated:
        Customer = request.user.customer
        orderitems = OrderItem.objects.filter(customer=Customer)
        order = orderitems[0].order
    else :
        orderitems = []
        order = {'get_cart_total':0,'get_number_of_items':0}
    context={'items':orderitems,'order':order}
    return render(request,'store/Checkout.html',context)

def Store(request):
    products = Product.objects.all()
    context = {'products':products}
    return render(request,'store/store.html',context)

Shopping/templates/store/Checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block body_block %}
<div class = "row">
    <div class = "col-lg-6">
        <div class = "box-element" id = "form-wrapper">
            <form id="form">
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email..">
                    </div>
                </div>
                
                <div id="shipping-info">
                    <hr>
                    <p>Shipping Information:</p>
                    <hr>
                    <div class="form-field">
                        <input class="form-control" type="text" name="address" placeholder="Address..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="city" placeholder="City..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="state" placeholder="State..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="country" placeholder="Zip code..">
                    </div>
                </div>

                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>
        </div>
        <br>
            <div class="box-element hidden" id="payment-info">
                <small>Paypal Options</small>
            </div>
    </div>
    <div class = "col-lg-6">
        <div class = "box-element">
            <a  class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
                <hr>
                {% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{ item.product.image.url }}"></div>
                    <div style="flex:2"><p>{{ item.product.name }}</p></div>
                    <div style="flex:1"><p>${{ item.product.price }}</p></div>
					<div style="flex:1"><p>x{{ item.quantity }}</p></div>
                </div>
                {% endfor %}
				<h5>Items:   {{ order.get_number_of_items }}</h5>
				<h5>Total:   ${{ order.get_cart_total }}</h5>
        </div>
    </div>
</div>
{% endblock %}

Shopping/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block body_block %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a  class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Items: <strong>{{ order.get_number_of_items }}</strong></h5></th>
                    <th><h5>Total:<strong> ${{ order.get_cart_total }}</strong></h5></th>
                    <th>
                        <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>
        <br>
        <div class="box-element">
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{ item.product.image.url }}"></div>
                <div style="flex:2"><p>{{ item.product.name }}</p></div>
                <div style="flex:1"><p>${{ item.product.price }}</p></div>
                <div style="flex:1">
                    <p class="quantity">{{ item.quantity }}</p>
                    <div class="quantity">
                        <img class="chg-quantity" src="{% static  'images/arrow-up.png' %}">
                
                        <img class="chg-quantity" src="{% static  'images/arrow-down.png' %}">
                    </div>
                </div>
                <div style="flex:1"><p>${{ item.cost }}</p></div>
            </div>
            {% endfor %}
        </div>
</div>
{% endblock %}

Shopping/templates/store/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecom</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src = "{% static 'js/cart.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Ecom</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <div class="form-inline my-2 my-lg-0">
                   <a href="#"class="btn btn-warning">Login</a>
                   <a href="{% url 'store:cart' %}">
                     <img class="img-responsive" id="cart-icon" src="{% static 'images/cart.png' %}" height="40px">
                   </a>
                 <p id="cart-total">0</p>
               </div>
        </div>
      </nav>
      <div class = "container">
        {% block body_block %}
        {% endblock %}
      </div>
</body>
</html>

Shopping/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block body_block %}
<div class = "row">
    {% for object in products %}
    <div class = "col-lg-4">
        {% if object.image %}
        <img class = "thumbnail" src = "{{ object.image.url }}">
        {% else %}
        <img class = "thumbnail" src = "{% static 'images/placeholder.png' %}">
        {% endif %}
        <div class = "box-element product">
            <h6><strong>{{ object.name }}</strong></h6>
        <hr>
        <button  class="btn btn-outline-secondary add-btn">Add to Cart</button>
		<a class="btn btn-outline-success" href="#">View</a>
		<h4 style="display: block; float: right"><strong>${{ object.price }}</strong></h4>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}